baseURL = "https://melmothswunderkrammer.netlify.app/"
languageCode = "en-us"
title = "melmoth's wunderkammer"
theme = "PaperMod"

[markup.goldmark.renderer]
unsafe = true

[params]
customCSS = ["css/custom.css"]  # apunta a tu archivo dentro de assets/css/

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
      